version: '3'
services:
  test:
    environment:
    - ACCOUNT_SID=${ACCOUNT_SID}
    - AUTH_TOKEN=${AUTH_TOKEN}
    - APPLICATION_SID=${APPLICATION_SID}
    - API_KEY_SECRET=${API_KEY_SECRET}
    - API_KEY_SID=${API_KEY_SID}
    - BVER=${BVER}
    image: twilio-client:1.0.0
    build:
      args:
      - BVER=${BVER}
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    working_dir: /app
    container_name: twilio-client-integration-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
