version: 2.1

jobs:
  trigger-qe-tests:
    docker:
    - image: circleci/node:latest
    steps:
    - run:
        name: Trigger QE tests
        command: |
          curl --silent --output /dev/null -u "$CIRCLECI_API_AUTH_TOKEN": -X POST \
          --header "Content-Type: application/json" \
          -d '{"branch":"'v${CIRCLE_TAG:0:1}'","parameters":{"sdk_version":"'$CIRCLE_TAG'","is_rc":true}}' \
          $SDKS_QE_CIRCLECI_VOICE_JS_TESTS_ENDPOINT
workflows:
  release-candidate:
      jobs:
      - trigger-qe-tests:
          filters:
            tags:
              only:
              - /^\d+\.\d+\.\d+-rc\d+$/
              - /^\d+\.\d+\.\d+-preview\d+-rc\d+$/
              - /^\d+\.\d+\.\d+-beta\d+-rc\d+$/
            branches:
              ignore: /.*/
