version: '3'
# Note: This file is used to build run the integration tests.
#   for running integration tests
#   BROWSER=chrome BVER=stable docker-compose --file=./docker-compose.yml run integrationTests
#   to build container with browsers that will be used by integrationTests:
#   BROWSER=chrome BVER=stable docker-compose --file=./docker-compose.yml build browserContainer
#   to run bash for debugging the container:
#   BROWSER=chrome BVER=stable docker-compose --file=./docker-compose.yml run bash
services:
  defaults: &defaults
    user: root
    image: twilio/twilio-video-browsers:${BROWSER}-${BVER}
    working_dir: /opt/app
    cap_add:
      - NET_ADMIN
      - NET_RAW
  runtimeDefaults: &runtimeDefaults
    <<: *defaults
    environment:
    - ENVIRONMENT
    - ACCOUNT_SID
    - API_KEY_SID
    - API_KEY_SECRET
    - APPLICATION_SID
    - APPLICATION_SID_STIR
    - CALLER_ID
    volumes:
      - "../../:/opt/app"
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/app/node_modules
  integrationTests: # runs integration tests. Expects that sources are mounted.
    <<: *runtimeDefaults
    command: bash -c "npm install --legacy-peer-deps && npm run build && ls -la /root && ls -la /root/.npm && npm run test:network"
  bash: # runs bash shell inside container. helpful for debugging
    <<: *runtimeDefaults
    command: bash
  getVersion: # print browser version installed in the container.
    <<: *runtimeDefaults
    command: /opt/app/.circleci/images/printbrowserversion.sh
